function generator$places$realms() {
	var names6 = ["Abandoned", "Abyss", "Ageless", "All", "Amber", "Ancestor", "Ancient", "Animated", "Aquamarine", "Arctic", "Argent", "Ash", "August", "Autumn", "Azure", "Barbarian", "Barren", "Black", "Boiling", "Bone", "Broken", "Burning", "Calm", "Celestial", "Center", "Cerulean", "Cinder", "Cloud", "Conjured", "Conscious", "Cosmic", "Covert", "Crimson", "Cyber", "Dead", "Delusion", "Demi", "Desolate", "Destiny", "Divine", "Dormant", "Double", "Dragon", "Dream", "Dual", "Dying", "Ebon", "Echo", "Eclipse", "Edge", "Elder", "Ember", "Emerald", "Empty", "Enchanted", "Enigma", "Eternal", "Ethereal", "Ever", "Everday", "Fading", "Fantasy", "Fate", "Feral", "Fierce", "Final", "Flaming", "Floating", "Flowing", "Forged", "Forsaken", "Fortune", "Fractioned", "Frenzied", "Frozen", "Future", "Gentle", "Ghost", "Giant", "Glowing", "God", "Golden", "Hallowed", "Harsh", "Hell", "Hibernating", "Hidden", "Hollow", "Howling", "Ice", "Illusion", "Imagined", "Immortal", "Infernal", "Inferno", "Injured", "Invisible", "Iron", "Ivory", "Jade", "Legend", "Lifeless", "Limbo", "Living", "Lonely", "Lunar", "Lush", "Lustrous", "Mad", "Magic", "Malachite", "Mammoth", "Manifested", "Maroon", "Merciless", "Migrating", "Mimic", "Miniature", "Miracle", "Mirage", "Mirror", "Mist", "Mock", "Monster", "Mortal", "Moving", "Multi", "Mythic", "Nebula", "Nether", "Never", "Night", "Nightmare", "Nimbus", "Noble", "Oblivion", "Obscure", "Obsidian", "Onyx", "Oracle", "Paralyzed", "Parallel", "Past", "Patriarch", "Peaceful", "Perfect", "Perpetual", "Phantom", "Portal", "Pure", "Rabid", "Rain", "Regal", "Riddle", "Rune", "Sacred", "Sanguine", "Sapphire", "Savage", "Scarlet", "Second", "Severed", "Shadow", "Shattered", "Shifting", "Shivering", "Shrouded", "Silver", "Single", "Sinking", "Skeletal", "Sky", "Slumbering", "Snow", "Solar", "Solitary", "Soul", "Specter", "Spirit", "Spring", "Steam", "Sterile", "Storm", "Summer", "Tamed", "Tempest", "Temporary", "Terminal", "Thunder", "Timeless", "Titan", "Trance", "Transient", "Treacherous", "Trial", "Twilight", "Twin", "Undying", "Utopia", "Virtual", "Vision", "Void", "Wandering", "White", "Whole", "Wild", "Windy", "Winter", "Wonder"];
	var names7 = ["Country", "Domain", "Dominion", "Earth", "Empire", "Expanse", "Fields", "Forest", "Isle", "Isles", "Lake", "Land", "Lands", "Moon", "Nation", "Nexus", "Ocean", "Plane", "Planet", "Province", "Reach", "Realm", "Realms", "Region", "Sanctuary", "Sanctum", "Sea", "Terrain", "Territories", "Territory", "Universe", "Vale", "Vales", "Valley", "World", "Yonder"];

	rnd = Math.floor(Math.random() * names6.length);
	rnd2 = Math.floor(Math.random() * names7.length);
	names = names6[rnd] + " " + names7[rnd2];

	return names;
}